### ISSUE TITLE
Typesense "infix" option as an optional part of the Field Definition 

### ISSUE THREAD

**Issue by AdamGilliesSA** [DAXGRID/typesense-dotnet#101]
Hello ,

Would it be possible to add the "infix" behaviour as an optional field definition parameter?

Here is the documentation for the function:

![image](https://user-images.githubusercontent.com/105202941/195471349-1fc09be1-b63b-4119-a51b-54fdcadbe25c.png)

The original issue is outlined here: https://github.com/typesense/typesense/issues/393

**Comment by runeanielsen** [comment]
Hi @AdamGilliesSA, thank you for finding the missing field `Infix`.

I've now added `Infix` to the `Field` type and to the `SearchParameters` in #102. Remember to also specify "off", "always" and "fallback" in the `SearchParameters` as described in the docs. 

I'll make a new release with the issue fixed. :)

// Rune

**Comment by AdamGilliesSA** [comment]
Thank you again for the quick update :)
