### ISSUE TITLE
split_join_tokens sends boolean instead of off | fallback | always

### ISSUE THREAD

**Issue by geisterfurz007** [DAXGRID/typesense-dotnet#107]
https://typesense.org/docs/0.23.1/api/search.html#typo-tolerance-parameters documents split_join_tokens to be either one of `off`, `fallback` or `always` but the library sends boolean values.

This seems to be an undocumented breaking change between typesense 0.23.0 and 0.23.1 (nice semver going on...); The docs for 0.23.0 still define it as true / false: https://typesense.org/docs/0.23.0/api/search.html#query-parameters

*I don't depend on this, I just noticed it and figured I'd document it :)*

**Comment by runeanielsen** [comment]
@geisterfurz007 thanks, I'll take a look at it.
