### ISSUE TITLE
HttpClient timeout when deleting huge collection

### ISSUE THREAD

**Issue by georgeemr** [DAXGRID/typesense-dotnet#110]
Httpclient timeouts after 100 seconds when trying to remove a collection with 700k records.
Is there a way to override the HTTP client on the AddTypesenseClient so I can extend this time? 
Or do you recommend a better way to delete it.
Thanks

**Comment by runeanielsen** [comment]
Hi @georgeemr, thanks for opening the issue.

You should be able to override the default `HttpClient` doing setup.

Here is an example of setting the `TimeOut` to 6 mins.

```C#
        var provider = new ServiceCollection()
            .AddTypesenseClient(config =>
            {
                config.ApiKey = "key";
                config.Nodes = new List<Node> { new Node("localhost", "8108", "http") };
            }).AddHttpClient<ITypesenseClient, TypesenseClient>()
            .ConfigureHttpClient(x =>
            {
                x.Timeout = TimeSpan.FromSeconds(360);
            })
            .Services
            .BuildServiceProvider();
```
