### ISSUE TITLE
Support snippets/matches for array types 

### ISSUE THREAD

**Issue by PhenX** [DAXGRID/typesense-dotnet#119]
For now, we cannot access snippets, matches and indices for array types, like described here : 

https://typesense.org/docs/0.23.1/api/search.html#search-parameters

      "highlights": [
        {
          "field": "addresses",
          "indices": [0,2],
          "snippets": [
            "10880 <mark>Malibu</mark> Point, <mark>Malibu,</mark> CA 90265",
            "10000 <mark>Malibu</mark> Point, <mark>Malibu,</mark> CA 90265"
          ],
          "matched_tokens": [
            ["Malibu", "Malibu"],
            ["Malibu", "Malibu"]
          ]
        }
      ],

**Comment by runeanielsen** [comment]
This is fixed in #129
