### ISSUE TITLE
search Filters and geoSearch

### ISSUE THREAD

**Issue by Boonthrall** [DAXGRID/typesense-dotnet#132]
Are search filters and geoSearch already supported with this client or do they have to yet be added?
If it exists, how can they be used and if not, could it please be implemented?

**Comment by runeanielsen** [comment]
Search filters are supported and `geopoint` and `geopointarray` can be found on the `FieldType` class. https://github.com/DAXGRID/typesense-dotnet/blob/master/src/Typesense/FieldType.cs#L17.

**Comment by Boonthrall** [comment]
Hey @runeanielsen 
Sorry to open the issue again, just wanted to say thank you i managed to do what i wanted to.
I seem to have missed some things when i made the issue.
