### ISSUE TITLE
Nested Fields/Objects

### ISSUE THREAD

**Issue by DaneAffinity** [DAXGRID/typesense-dotnet#133]
Hi,

I'm looking to make use of the new features implemented in Typesense v0.24.0. 

The Object and Object[] Field types have been added. [doc](https://typesense.org/docs/0.24.0/api/collections.html#field-types)
The property enabled_nested_fields has been added to document creation. [doc](https://typesense.org/docs/guide/tips-for-searching-common-types-of-data.html#nested-objects)

Would it be able to have these added to make use of indexing nested objects?

Thanks,
Dane.

**Comment by runeanielsen** [comment]
Hi @DaneAffinity,

Thanks for opening the issue, I'll take a look at it this week.

// Rune

**Comment by runeanielsen** [comment]
This has been fixed in #135. I'll make a new release with the added features. I'll take a look at some of the other changes in Typesense 0.24.0 when I've the time.

**Comment by runeanielsen** [comment]
@DaneAffinity now released in version 6.1.0.

**Comment by runeanielsen** [comment]
@DaneAffinity here is an example of how to create a `Schema` with nested fields.

```C#
var schema = new Schema(
    "companies",
    new List<Field>
    {
        new Field("company_name", FieldType.String, false),
        new Field("num_employees", FieldType.Int32, true),
        new Field("location", FieldType.Object, true),
    },
    "num_employees")
{
    EnableNestedFields = true
};
```

**Comment by DaneAffinity** [comment]
Thanks @runeanielsen, will check this out tomorrow.
