### ISSUE TITLE
README missing Vector Query documentation

### ISSUE THREAD

**Issue by tanczosm** [DAXGRID/typesense-dotnet#148]
I forgot about this aspect but the README should probably be updated to include information regarding vector queries.

## Vector Search

Typesense supports the ability to add embeddings generated by your Machine Learning models to each document, and then doing a nearest-neighbor search on them. This lets you build features like similarity search, recommendations, semantic search, visual search, etc.  Here is an example of how to create a vector schema, a vector document, and perform a multi search using a vector as a query parameter.

```csharp
const string COLLECTION_NAME = "address_vector_search";

var schema = new Schema(
    COLLECTION_NAME,
    new List<Field>
    {
        new Field("vec", FieldType.FloatArray, 4)
    });

_ = await _client.CreateCollection(schema);

await _client.CreateDocument(
    COLLECTION_NAME,
    new AddressVectorSearch()
    {
        Id = "0",
            Vec = new float[] { 0.04F, 0.234F, 0.113F, 0.001F }
    });

var query = new MultiSearchParameters(COLLECTION_NAME, "*")
{
    // vec:([0.96826, 0.94, 0.39557, 0.306488], k:100)
    VectorQuery = new(
        vector: new float[] { 0.96826F, 0.94F, 0.39557F, 0.306488F },
        k: 100)
};

var response = await _client.MultiSearch<AddressVectorSearch>(query);
```

**Comment by runeanielsen** [comment]
Thanks, I'll add it to the readme :+1:

**Comment by runeanielsen** [comment]
@tanczosm this has now been added in #149
