### ISSUE TITLE
Object and ObjectArray fieldtype

### ISSUE THREAD

**Issue by Boonthrall** [DAXGRID/typesense-dotnet#151]
Hey, i'm opening this issue to ask about the functionality of the object and objectarray field types.
Typesense themselves don't support object field types, how is this translated in this library?

**Comment by runeanielsen** [comment]
Hi @Boonthrall,

This was added in this PR https://github.com/DAXGRID/typesense-dotnet/issues/133.

// Rune

**Comment by Boonthrall** [comment]
Ah, thank you!
