### ISSUE TITLE
VectorQuery doesn't work with Search - Malformed vector query string

### ISSUE THREAD

**Issue by HazyFish** [DAXGRID/typesense-dotnet#153]
Property `VectorQuery` exists on both `MultiSearchParameters` and `SearchParameters`. 
However, when using `Search` with `SearchParameters` that has a `VectorQuery`, the following error will occur:

```
Message: 
Typesense.TypesenseApiBadRequestException : {"message": "Malformed vector query string."}

Stack Trace: 
TypesenseClient.Get(String path, CancellationToken ctk)
TypesenseClient.SearchInternal[TResult](String collection, SearchParameters searchParameters, CancellationToken ctk)
TypesenseClient.Search[T](String collection, SearchParameters searchParameters, CancellationToken ctk)
```

**Comment by runeanielsen** [comment]
Hi @HazyFish, can you supply me with some example data and with the version of Typesense you're using.

// Rune

**Comment by HazyFish** [comment]
I'm using Typesense Nuget Package v6.4.0.

### Works using `MultiSearch` and `MultiSearchParameters`

```cs
var searchParams = new MultiSearchParameters(GetCollectionName(), "*")
{
    VectorQuery = new(new float[] { 0f, 1f, 2f, 3f }),
};

var searchResult = await typesenseClient.MultiSearch<Model>(searchParams);

### Doesn't work using `Search` and `SearchParameters` to do the same thing

```cs
var searchParams = new SearchParameters("*")
{
    VectorQuery = new(new float[] { 0f, 1f, 2f, 3f }),
};

await typesenseClient.Search<Model>(GetCollectionName()), searchParams);
```

**Comment by runeanielsen** [comment]
Hi @HazyFish, 

Thanks for pointing out the issue, I looked at the Typesense docs and vector search can only be done using MultiSearch, I'll make a fix to the library so `VectorQuery` is only available on `MultiSearchParameters`, luckily this won't break any consumers of the library.

// Rune

**Comment by runeanielsen** [comment]
Fixed in #156

**Comment by runeanielsen** [comment]
Made a new hotfix release https://github.com/DAXGRID/typesense-dotnet/releases/tag/6.4.1 with the changes.

**Comment by HazyFish** [comment]
Thank you so much!
