### ISSUE TITLE
Support Auto-embedding & Hybrid Search for v0.25.x

### ISSUE THREAD

**Issue by HazyFish** [DAXGRID/typesense-dotnet#157]
Typesense v0.25.0 now supports [Auto Embedding Generation](https://typesense.org/docs/0.25.0/api/vector-search.html#option-b-auto-embedding-generation-within-typesense) and [Hybrid Search](https://typesense.org/docs/0.25.0/api/vector-search.html#hybrid-search).

I wonder if the support is on the way. If not, I can contribute.

**Comment by runeanielsen** [comment]
Hi @HazyFish,

Nothing from Typesense v0.25.0 has been implemented yet. Feel free to give it a go if you want to.

// Rune

**Comment by HazyFish** [comment]
I can work on it!

**Comment by HazyFish** [comment]
There seems to be an upstream bug unrelated to semantic search that broke the integration test cases for document export when using v0.25.0. I have reported the problem (https://github.com/typesense/typesense/issues/1166). Just to keep you in the loop.

**Comment by runeanielsen** [comment]
Added in #158
