### ISSUE TITLE
Missing assembly references for Unity

### ISSUE THREAD

**Issue by sgm55** [DAXGRID/typesense-dotnet#160]
Hi, I'm trying to import the typesense .NET package on Unity with Nuget, but I am getting the following error:

Error Could not install package 'Typesense 6.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Any guidance will be greatly appreciated, thanks in advance!

**Comment by runeanielsen** [comment]
Hi @sgm55,

We currently only target .NET 5.0 + so it sadly won't work for you. It's been a feature quest to target .NET standard instead, but it will break a lot of the existing users, so I won't be doing that in the near future.

// Rune

**Comment by sgm55** [comment]
Ok, thanks for your prompt response @runeanielsen
