### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by wbasterfield** [DAXGRID/typesense-dotnet#161]
Hi there

I'm experiencing a timeout when ingesting a lot of data using autoEmbedding.
It all works fine for small models like ts/e5-small.
When using ts/e5-large-v2 there is a 100 sec timeout.

Is there a way to extend the timeout ?

**Comment by runeanielsen** [comment]
Hi @wbasterfield,

Take a look at the answer I've given in this issue and see if it solves your problem https://github.com/DAXGRID/typesense-dotnet/issues/110.

If not, please write here again and I'll take a look.

// Rune
