### ISSUE TITLE
Implement Healthcheck

### ISSUE THREAD

**Issue by MeikelLP** [DAXGRID/typesense-dotnet#163]
You can do a healtcheck via `/health` endpoint.

Typesense startup is kinda messy and checking for healthiness works for now so I'm relying on that feature quite heavily. Would be nice if this client would make this easier :)

**Comment by runeanielsen** [comment]
Hi @MeikelLP,

I'll take a look at it in the coming week.

// Rune

**Comment by MeikelLP** [comment]
Looks good
