### ISSUE TITLE
The XML documentation is not included the NuGet package

### ISSUE THREAD

**Issue by aradalvand** [DAXGRID/typesense-dotnet#167]
Hi. The XML documentation on properties and whatnot (e.g. `<summary>` tags, etc.) aren't actually included in the NuGet package. For example, `SearchParameters.Text` has this `<summary>`:
https://github.com/DAXGRID/typesense-dotnet/blob/0e59b48fbe51903c256fab332b4ac2cf7a48f3c4/src/Typesense/SearchParameters.cs#L49-L55

Yet when you install the `Typesense` package, this is nowhere to be seen:

![image](https://github.com/DAXGRID/typesense-dotnet/assets/26527405/192ec730-491c-4217-a922-abc942b31c6c)

[NuGet's package explorer](https://nuget.info/packages/Typesense/6.7.0) also shows that there is no `.xml` file included in the package:

![image](https://github.com/DAXGRID/typesense-dotnet/assets/26527405/9960c4e7-2b3b-43a2-9224-1f09e8e724e8)

Contrast this with [EF Core](https://nuget.info/packages/Microsoft.EntityFrameworkCore/6.0.0-rc.1.21452.10), for instance:

![image](https://github.com/DAXGRID/typesense-dotnet/assets/26527405/48dca523-2af0-4cb6-934b-424ec32a8d61)

This is because the `<GenerateDocumentationFile>true</GenerateDocumentationFile>` setting is missing in your .csproj file — see [this](https://stackoverflow.com/q/43305578/7734384).
I can make a PR for this, let me know if you're on board.

**Comment by runeanielsen** [comment]
Hi @aradalvand,

Feel free to make a PR with the change. :+1: 

// Rune
