### ISSUE TITLE
Unable to use custom Vector Query for Hybrid Semantic searches

### ISSUE THREAD

**Issue by keith-rvezy** [DAXGRID/typesense-dotnet#182]
As per docs [here](https://typesense.org/docs/0.25.1/api/vector-search.html#distance-threshold) for setting the distance threshold on our embeddings we cannot do so in the current client. The existing ParseQuery is requiring the vector query to start with vec: and not allowing a custom field like embedding: . 

Additionally, would be more useful to allow setting this vector query after the constructor and not having the property set to init.

**Comment by runeanielsen** [comment]
Hi @keith-rvezy,

Thanks for opening the issue, can you provide some example that showcases what you want to do and why it is not possible, as well as showcasing an example of how you would like the client to work.

Thanks,
Rune

**Comment by runeanielsen** [comment]
Closed due to inactivity.
