### ISSUE TITLE
Providing with found_docs field when grouped searching

### ISSUE THREAD

**Issue by eastwing27** [DAXGRID/typesense-dotnet#190]
If I send a REST request to our Typesense instance which includes both grouping and faceting, it returns, among the other data, two fields:

- `found`, which is number of matched groups 
- `found_docs `which is the number of all the matched docs before they were grouped

We really need both. However, typesense-dotnet provides us with `Found` field only, could you please add FoundDocs field as well?

REST request example:
`http://our-ts-instance/collections/Products/documents/search?q=*&facet_by=modelId&group_by=modelId`

REST response example:
```
{
    "facet_counts": [
        {
            "counts": [...],
            "field_name": "modelId",
            "sampled": false,
            "stats": {
                "total_values": 9220
            }
        }
    ],
    "found": 9220,
    "found_docs": 11861, //this
    "grouped_hits": [...],
    // etc
}
```

Note: OutOf field is not what we're looking for as it is the collection size while we need to get the total amount of docs matched the search/filter query

**Comment by runeanielsen** [comment]
@eastwing27 the property has now been added and is named `FoundDocs`. I've release a new version `7.1.0`.

Let me know if it fixes your problem.

// Rune
