### ISSUE TITLE
JOIN support

### ISSUE THREAD

**Issue by comichael** [DAXGRID/typesense-dotnet#201]
Typesense is working to add JOIN support, based on a "reference", similar to foreign keys in a DB:

https://gist.github.com/kishorenc/037314619c3104970ae703b25aff2f51#many-to-many-relation

This is still in the making (not official, but a RC / branch), per feb 2024.

However, how could we add support for this using typesense-dotnet? Would it be as simple as adding a  reference field in the Field class?

https://github.com/typesense/typesense/issues/229#issuecomment-1959467563

**Comment by runeanielsen** [comment]
Hi @comichael,

Let me think about it for a few days and I'll get back to you. The reason that I am hesitant to implement it, is because it is not a finished feature yet.

// Rune

**Comment by runeanielsen** [comment]
@runeanielsen this has now been released in version 7.2.0. The `Field` type now has a `Reference` field that can be used to support joins, like the feature was described in the linked Typesense issue #229.

// Rune
