### ISSUE TITLE
Add support for JOINs?

### ISSUE THREAD

**Issue by steingran** [DAXGRID/typesense-dotnet#207]
Typesense v26 is released, and one of the new features there is JOINs: https://typesense.org/docs/26.0/api/joins.html

Have anyone started thinking about how to add support for JOINS to the typesense-dotnet project? This seems to be a feature I would like to use in a project I'm working on, and I can try to contribute to this feature unless anyone has already done some work on this?

**Comment by runeanielsen** [comment]
@steingran feel free to make the contribution. 

// Rune

**Comment by runeanielsen** [comment]
Closing this since it has been answered.
