### ISSUE TITLE
Generate Scoped Search Key: Handy method

### ISSUE THREAD

**Issue by backrightupcom** [DAXGRID/typesense-dotnet#22]
I needed to generate a search scope key for my [Azure devops backup](https://backrightup.com) app :

https://typesense.org/docs/0.19.0/api/api-keys.html#generate-scoped-search-key

Other frameworks have this built in, so i added my own. The code HASNT been cleaned up, but Im leaving this here to help someone else. Sorry I don't have time for a PR right now but may come back later!

![image](https://user-images.githubusercontent.com/81234491/125548109-0f05788f-9180-4b9c-bd98-f72c4e68542b.png)

**Comment by runeanielsen** [comment]
The pull-request (#25) can be used to create and manage IP-keys with scopes(actions)  My understanding is that it should be able to manage all the features that are described in this post, if not please open a new issue with a reference to this issue, thanks. :)
