### ISSUE TITLE
When an unknown status code is hit... you get an unuseful exception

### ISSUE THREAD

**Issue by jonathan-rvezy** [DAXGRID/typesense-dotnet#225]
Would it be possible to change this to expose the code and message?

https://github.com/DAXGRID/typesense-dotnet/blob/092aa1f9ec81bd0e5aed6e9d43c69eb79c6aeae3/src/Typesense/TypesenseClient.cs#L713

**Comment by runeanielsen** [comment]
Hi @jonathan-rvezy, yes, I'll take a look at this, this week.

// Rune
