### ISSUE TITLE
Add support for additional field parameters

### ISSUE THREAD

**Issue by jfern01** [DAXGRID/typesense-dotnet#232]
Me again. The library is missing support for new(ish) field parameters "vec_dist" and "range_index": https://typesense.org/docs/26.0/api/collections.html#field-parameters

Those two are the only ones missing from what I can tell.

**Comment by runeanielsen** [comment]
Hi @jfern01,

I'll take a look at it in the next couple of days. :)

// Rune

**Comment by runeanielsen** [comment]
Hi @jfern01 can you confirm that the field

"vec_dist" should be a `string` type and that "range_index" is a boolean type?

// Rune

**Comment by jfern01** [comment]
"vec_dist" seems to be a string with enum values "cosine" or "ip".

"range_index" is indeed a boolean.

Thanks for looking into this.

**Comment by runeanielsen** [comment]
I'll make the "vec_dist" a simple string that way if it changes the client library won't have to change.

**Comment by runeanielsen** [comment]
@jfern01 this has now been released in version 7.13.0. 

I hope it fixes your problem. :)

// Rune
