### ISSUE TITLE
Search query parameters are missing

### ISSUE THREAD

**Issue by adonistseriotis** [DAXGRID/typesense-dotnet#235]
First, I'd like to thank the contributors for their work on this wrapper! It has been proven very helpful to me. 

I wanted to note that some search parameters like `facet_return_parent` are missing from the `SearchParameters` class.

Is it possible that you add them, or I can create a PR if you'd like adding this attribute. 

Thanks in advance

**Comment by adonistseriotis** [comment]
Okay, after having a look at your code, to my understanding, if I add this attribute to the class it should work right?

**Comment by runeanielsen** [comment]
Yes, I am pretty sure it should just work. :)

**Comment by adonistseriotis** [comment]
@runeanielsen just created the PR, I have tested it locally so if you can check it out and maybe release a new patch it would be great! 🫡

**Comment by runeanielsen** [comment]
Hi @adonistseriotis,

I'll have to look through it tomorrow, I can see that the tests are failing, will let now know here when I know more.


// Rune

**Comment by adonistseriotis** [comment]
@runeanielsen I saw that too, I will update my pull request with optionality on the parent attribute I added and the tests should pass afterwards.

**Comment by runeanielsen** [comment]
Hi @adonistseriotis, thanks for the contribution, I've made a new release with tag 7.15.0 that contains the changes.
