### ISSUE TITLE
Provide a way to create a Typesense client without IOptions

### ISSUE THREAD

**Issue by isaacabraham** [DAXGRID/typesense-dotnet#249]
I could not find a way to create a Typesense client without the close coupling to IOptions and the whole Service Collection stuff. Is there no way in the API to simply pass in basic arguments like API Key and the host of the server directly to the Typesense Client?

**Comment by runeanielsen** [comment]
Hi @isaacabraham,

You will always have to use the Options, I regret making it that way, but I don't want breaking changes so that is how it is now.

Here is an example of how to do it without using the service collection.


```C#
        var myConfig = new Config(
            new List<Node>()
            {
                new Node("myhost", "8000", "http")
            }.AsReadOnly(),
            "myKey"
        );

        using var myHttpClient = new HttpClient();

        var myTypesenseClient = new TypesenseClient(Options.Create<Config>(myConfig), myHttpClient);
```

// Rune

**Comment by isaacabraham** [comment]
Thanks for the reply! I'm curious as to why this would be a breaking change - could an override be added to the constructor? This way, the existing codepath could remain, but the alternative would also be permitted.

Thanks :-)

**Comment by runeanielsen** [comment]
@isaacabraham you're right it will only be a breaking change if I were to change the current constructor, it would be no issue with constructor overloading, I'll think about it and let you know what I decide on. :)

**Comment by runeanielsen** [comment]
Actually it is a problem with constructor overloading, apparently the service collection cannot figure out there is a difference between the `IOptions<Config>` and the `Config`. 

System.InvalidOperationException : Multiple constructors accepting all given argument types have been found in type 'Typesense.TypesenseClient'. There should only be one applicable constructor.

For now I'll leave it as it is, but I might reopen the issue in the future in case that I decide to make the breaking change.
