### ISSUE TITLE
feature request - return_id when document import

### ISSUE THREAD

**Issue by nathanblogs** [DAXGRID/typesense-dotnet#255]
it would be good to be able to use this feature https://typesense.org/docs/0.25.1/api/documents.html#index-multiple-documents

**Comment by runeanielsen** [comment]
Hi @nathanblogs, you should be able to index multiple elements already.

https://github.com/DAXGRID/typesense-dotnet?tab=readme-ov-file#import-documents

**Comment by runeanielsen** [comment]
Sorry, didn't see the title, I'll take a look this weekend I think about the `return_id`

**Comment by runeanielsen** [comment]
@nathanblogs fixed in add return id flag on import documents (#258)

**Comment by runeanielsen** [comment]
@nathanblogs relased in 7.22.0
