### ISSUE TITLE
Question about Multi-tenant Support

### ISSUE THREAD

**Issue by trentstollery-millow** [DAXGRID/typesense-dotnet#259]
Hey!
Great package, looking forward to using it.
I was just wondering what would be the best way to support Multi-tenant api keys?
I thought maybe setting up a new client then disposing it for each api call but I'm not sure the client supports being create via anything other than DI.
Is it possible to change the API key config in the client after it is created by DI.
Any idea?

**Comment by trentstollery-millow** [comment]
Note to those that came after me, I found a work around for this
```
 var apiKey = "";
 List<Node> nodes = [];
 var config = new Typesense.Setup.Config(nodes,apiKey);
 this._client = new TypesenseClient(Options.Create(config),httpClient);

```

I works.. however I feel it could be cleaner... I may fix this in a PR later on

**Comment by runeanielsen** [comment]
Hi @trentstollery-millow,

If you're going to make a PR, make sure not to break the existing API.

**Comment by trentstollery-millow** [comment]
Of course! I'll add tests as needed as well

**Comment by trentstollery-millow** [comment]
Sorry I missed the first part of that comment, generally I would agree however... I was a little confused as to why this use case wasn't supported. As it is one of the major features that is advertised for typesense and using the current setup via dep injection it just doesn't really work at all. 
I'm of two minds as to if it's worth creating a PR as it seems like this wasn't one of the goals of this typesense-dotnet, I don't want to force support for something most of this userbase won't use.  However I do feel this is a important feature that should be supported at the client level, not really something that each user should work out how to support. I'll leave it for now and come back to it after xmas.
