### ISSUE TITLE
The type of MatchedTokens should be IReadOnlyList<object>

### ISSUE THREAD

**Issue by yunzeli029** [DAXGRID/typesense-dotnet#30]
https://github.com/DAXGRID/typesense-dotnet/blob/14a5ae051625e651f2ac500f01e5bebf3e1ee976/src/Typesense/SearchResult.cs#L13

Hi, I have a deserialized exception after querying by an attribute, the attribute has an array type in Typesense.

The matches token would return 2-D string array instead of 1-D string array. I think it could be a bug in Typesense as the match token only contains the first item that matches the query. 

In this case, I think it could be better to change the type of MatchedTokens to IReadOnlyList<object>.

**Comment by runeanielsen** [comment]
Hi @yunzeli029,

I just checked one of Typesense own clients and they match being a list of strings  https://github.com/typesense/typesense-js/blob/7195ea9beb12b78e913dec7b6dc934b90fac0244/src/Typesense/Documents.ts#L73

Can you show me an example of your collection schema and how you search on it?

**Comment by yunzeli029** [comment]
Sure.

If we create a company collection with this schema
```
{
    "name": "companies",
    "fields": [
        {
            "name": "company_name",
            "type": "string[]"
        }
    ]
}
```
And import the data
```
{"id": "124","company_name": ["Stark Industries", "Stark"]}
{"id": "125","company_name": ["Acme Corp"]}
```

When I query `Stark `, the match token would be 
```
"matched_tokens": [
                        [
                            "Stark"
                        ],
                        [
                            "Stark"
                        ]
                    ],
```

**Comment by runeanielsen** [comment]
@yunzeli029 I found in their docs under sample response (https://typesense.org/docs/0.21.0/api/documents.html#search)

```
When a string[] field is queried, the highlights structure would include the corresponding matching array indices of the snippets. For e.g:

{
      ...
      "highlights": [
        {
          "field": "addresses",
          "indices": [0,2],
          "snippets": [
            "10880 <mark>Malibu</mark> Point, <mark>Malibu,</mark> CA 90265",
            "10000 <mark>Malibu</mark> Point, <mark>Malibu,</mark> CA 90265"
          ],
          "matched_tokens": [
            ["Malibu", "Malibu"],
            ["Malibu", "Malibu"]
          ]
        }
      ],
      ...
}
```

So it is the expected behavior, I'll try to come up with a fix. I'll let you know when it is fixed.

**Comment by yunzeli029** [comment]
Thanks for your help @runeanielsen

**Comment by runeanielsen** [comment]
@yunzeli029 this has been fixed in this https://github.com/DAXGRID/typesense-dotnet/pull/31.

I'll release a new package with version `2.2.2`
