### ISSUE TITLE
Partial updates

### ISSUE THREAD

**Issue by TariqHattab** [DAXGRID/typesense-dotnet#98]
Hello, can I do partial updates with UpdateDocument ? can you give a small example of how to pass the values since it takes an object , Thank you

**Comment by runeanielsen** [comment]
Hi @TariqHattab,

All null values won't be sent to the Typesense server, so you can just create a new object, and set the values you wish to partially update. Remember that it is required to always set the `Id` field, so Typesense can find the document you want to update.

```c#
var address = new Address { Id = "1", HouseNumber = 25 };
var updateDocumentResult = await typesenseClient.UpdateDocument<Address>("Addresses", "4", address);
```

Another way to do it, is using a dynamic object. 

```c#
var updateDocumentResult = await typesenseClient.UpdateDocument<dynamic>("Addresses", "4", new { HouseNumber = 25, Id = "4" });
```

Hope this helps.


// Rune

**Comment by TariqHattab** [comment]
Hello @runeanielsen , Thank you very much for the detailed answer, do you know if there is a way to delete a field ? because if i put it to null it would not update it , or should i just overwrite by upsert?

**Comment by runeanielsen** [comment]
@TariqHattab you will have to update it using an upsert, but remember that upsert updates all fields. :)

**Comment by TariqHattab** [comment]
Ok Thank you very much.
