### ISSUE TITLE
Searching fields with `_` and `-` using token_separators

### ISSUE THREAD

**Issue by AdamGilliesSA** [DAXGRID/typesense-dotnet#99]
Is it possible to get support for this issue with Typesense search:

https://github.com/typesense/typesense/issues/122

My understanding is that we will need to set `token_separators` as part of the document creation process.

If there is already a method to do this then would it be possible to give an example of how to set it up.

Thanks,
Adam

**Comment by runeanielsen** [comment]
Hi @AdamGilliesSA, thanks for opening the issue.

I've implemented the missing fields on the `Schema` type, so there is now support for the `token_separators` and `symbols_to_index` fields in version `4.5.0` of the client.

Here is an example where I set both of them

```C#
        var schema = new Schema(
            "companies_with_symbols_and_token",
            new List<Field>
            {
                new Field("company_name", FieldType.String, false),
                new Field("num_employees", FieldType.Int32, true),
                new Field("country", FieldType.String, true),
            },
            "num_employees")
        {
            TokenSeparators = new List<string> { "-" },
            SymbolsToIndex = new List<string> { "+" }
        };
```

// Rune

**Comment by AdamGilliesSA** [comment]
Thank for you this! Much Appreciated :)
